# Generated by Django 2.1.2 on 2019-03-20 16:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('text', models.TextField()),
                ('message_ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, default='message_pictures/None/default.png', null=True, upload_to='message_pictures')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('name', models.CharField(max_length=40)),
                ('thread_ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('username', models.CharField(max_length=40, unique=True)),
                ('profile_img', models.ImageField(blank=True, default='profile_pictures/None/default.png', null=True, upload_to='profile_pictures')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='message',
            name='thread_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MessageApp.Thread'),
        ),
        migrations.AddField(
            model_name='message',
            name='user_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MessageApp.User'),
        ),
        migrations.AddField(
            model_name='member',
            name='thread_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MessageApp.Thread'),
        ),
        migrations.AddField(
            model_name='member',
            name='user_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MessageApp.User'),
        ),
    ]
