# Generated by Django 2.1.2 on 2019-03-19 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('text', models.TextField()),
                ('message_ID', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='')),
                ('date_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('name', models.CharField(max_length=40)),
                ('thread_ID', models.UUIDField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('f_name', models.CharField(max_length=30)),
                ('l_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=40, unique=True)),
                ('profile_img', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='thread_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MessageApp.Thread'),
        ),
        migrations.AddField(
            model_name='message',
            name='user_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MessageApp.User'),
        ),
        migrations.AddField(
            model_name='member',
            name='thread_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MessageApp.Thread'),
        ),
        migrations.AddField(
            model_name='member',
            name='user_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MessageApp.User'),
        ),
    ]
